### PR TITLE
added view, model and controller folders

### PR DESCRIPTION
**Pull request by kurtoria**

### CODE REVIEW

**Review by freddyJarva — COMMENTED** [review]
Did you push it to the limit?

**Comment by kurtoria** [comment]
lala

**Comment by kurtoria** [comment]
PUSH

**Comment by kurtoria** [comment]
IT

**Comment by kurtoria** [comment]
TO

**Comment by kurtoria** [comment]
THE

**Comment by kurtoria** [comment]
LIMIT

**Comment by freddyJarva** [comment]
Can you push it even to the limitererrer?

**Comment by kurtoria** [comment]
HEHEHEHE

**Comment by kurtoria** [comment]
ARE U PUSHIN IT TO THE LIMIT

**Comment by kurtoria** [comment]
THE...

...LIMIT?!?!!?!?!?!?!

**Comment by kurtoria** [comment]
PULL IT TO THE LIMIT

**Review by freddyJarva — APPROVED** [review]
The limit has been pushed?

**Pull request merged**
